### ISSUE TITLE
Editing Word Docs for BA Lead

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1012]
### Course
Please convert the 4 BA Lead courses for the [Proof of Concept](https://www.notion.so/twuid/TOP-Testing-Fall-2024-c345b1c5c37647b19c34f914f8c9f058) to word docs for editing.
Please check with IDs if there are changes to the course before conversion.

### Instructions
- [x] [LDRS 101](https://github.com/twu-innovation/inno101) - Next up for editing. Ready in quarto.  Can convert when production is ready.
- [x] [LDRS 330](https://github.com/BA-Leadership/LDRS330) (Mara)
- [x] [LDRS 400](https://github.com/BA-Leadership/ldrs400) (Natalia & Inok)
- [x] [LDRS 471](https://github.com/BA-Leadership/ldrs471/issues) (Mara, Ready for conversion)

Thank you!

**Comment by chloecwh** [comment]
Hi @kmarjanovic Can I know who's the ID for LDRS 101?

**Comment by chloecwh** [comment]
[LDRS 330 docs](https://github.com/BA-Leadership/LDRS330/issues/1) was sent over on Feb 12

**Comment by kmarjanovic** [comment]
Colin & I are IDs/SMEs for LDRS 101.  No changes for now, so ready to convert.

**Comment by Nataliadsanchez** [comment]
@Jeff-TWU we will send the revised Word docs with the changes next week (July 22-26)

**Comment by Jeff-TWU** [comment]
@chloecwh [INNO101](https://github.com/twu-innovation/inno101/tree/main/docs/INNO-101_split_docs) is ready for production review.

**Comment by Jeff-TWU** [comment]
@chloecwh [LDRS471](https://github.com/BA-Leadership/ldrs471/tree/main/docs/LDRS-471_split_docs) ready for production review

**Comment by chloecwh** [comment]
@Jeff-TWU [LDRS 330](https://github.com/BA-Leadership/LDRS330/tree/main/docs/LDRS-330_split_docs) ready for review

**Comment by Jeff-TWU** [comment]
> @Jeff-TWU [LDRS 330](https://github.com/BA-Leadership/LDRS330/tree/main/docs/LDRS-330_split_docs) ready for review

@chloecwh [Review complete](https://github.com/BA-Leadership/LDRS330/tree/main/word-docs/Rev_2). Looks good! I'll let you share it when you're ready.

 **A couple minor things:**

-  We can use references for both [figures](https://quarto.org/docs/authoring/cross-references.html#figures) and [topics (sections)](https://quarto.org/docs/authoring/cross-references.html#sections). I've added them in.

- We should use escape characters for quotes within alt text.
![Screenshot 2024-07-23 at 3 51 42 PM](https://github.com/user-attachments/assets/8604da4a-b76c-4056-98f0-07ff259eaa6f)

- If an image is using lightbox, then it should have a solid-coloured background. Otherwise it looks messy.
![Screenshot 2024-07-23 at 3 44 40 PM](https://github.com/user-attachments/assets/8438c3be-068a-4865-9ef1-911bf77a4018)

- My opinion is that for accessibility, many of these images should probably be turned into tables.

**Comment by chloecwh** [comment]
@Nataliadsanchez said that LDRS 400 will sent to editor before coming into production

**Comment by Nataliadsanchez** [comment]
Isn't it the process @kmarjanovic ?

**Comment by Nataliadsanchez** [comment]
@kmarjanovic @chloecwh @inoklim-twu LDRS 400 is ready for review by the editor. Please find the Course units in the [Learning Design folder](https://mytwu.sharepoint.com/sites/LearningDesign/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FLearningDesign%2FShared%20Documents%2FBA%2DLead%20Courses%20%2D%20Doc%2FLDRS%20400%2FCourse%20Content&viewid=40cf7fb5%2D2131%2D4adc%2Dbd1e%2D88296482bfbb)... Please let me know if it needs to be tracked somewhere else??
