### ISSUE TITLE
SOCI 101 Long Topic Lists

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#167]
### URL
https://learn.twu.ca/course/view.php?id=10781&section=5
### Instructions
Please add a click to expand feature for long topic lists for Units 4 & 5. (Show main topics, but not subtopics)

![image](https://user-images.githubusercontent.com/35148983/69885275-9823ca00-1299-11ea-8f8d-dff29e9bf2af.png)

**Comment by kmarjanovic** [comment]
I tried this...but needs work:
<details>
  <summary><b>1. Family</b></summary>
    <p><ul><li>a. Defining the family</li><li>b. Family change    
          </li><li> > 1. Family forms  </li><li> > 2. Work  </li><li>  >  3. Health  </li></ul>
    </p>
</details>

@cmadland any ideas?

**Comment by cmadland** [comment]
please check unit 5 @kmarjanovic 

It's not perfect, but maybe better than before.

**Comment by kmarjanovic** [comment]
Yes - that works!  Thanks!

**Comment by cmadland** [comment]
still working through why the MD isn't rendering inside the <details> tags...

**Comment by cmadland** [comment]
Ok...I realize my last comment was 6 hours ago...with small interruptions, I have been working on this since then. 
It's been sorted. the `details` tags are working AND the MD inside them is rendering!!

![image](https://user-images.githubusercontent.com/12282929/73796944-8bbd6100-4763-11ea-9dc5-8916d6ce1838.png)
