### ISSUE TITLE
TONE plugins & icons not working

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#287]
### Course
TONE
### URL
https://learn.twu.ca/course/view.php?id=13628&section=2
### Instructions
icons not working in Unit 2: Activity 2.2, 2.3, 2.5, 2.6, 2.7, Checking Your Learning - Assessment section.
Unit 4: 4.1, ...I'm sure there will be more as I'm finishing that unit.

**Comment by kmarjanovic** [comment]
Icons not working in some of the activity alerts and other content (see Unit 4 check your learning).
Please let me know the fix!

https://learn.twu.ca/course/view.php?id=13628&section=4

**Comment by cmadland** [comment]
The fix is to have the front matter as follows…

[cid:8E9E865E-98E8-413F-97AF-103BAE9C3F58@telus]

I’ll update the alerts in U4.

When you create another unit, just duplicate 1,2, or 4 and it should come along.

Colin


--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
604.513.2121 ext. 3876 |  colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.

On Apr 13, 2020, at 12:39 PM, Kelly Marjanovic <notifications@github.com<mailto:notifications@github.com>> wrote:



Icons not working in some of the activity alerts and other content (see Unit 4 check your learning).
Please let me know the fix!

https://learn.twu.ca/course/view.php?id=13628&section=4
