### ISSUE TITLE
Formatting Issue

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#443]
**Which course contains the bug?**  
- LDRS503 Dev Master
 
**Describe the error and/or your suggestion**  
I inserted the accordion (which works fine) but now I cannot get the formatting to work underneath (where it says "Individual Assignment #1: Preparation"
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13614&section=3
2. Unit #    1     Topic #    Resources     
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@dgaudet48 Hmmm that was a weird one. I couldn't figure it out either, so I threw the Individual Assignment info into an alert. In looking at the content, what do you think about moving that alert to live under the "Assessment" tab instead of under "Resources," since it has more to do with course assessments?
