### ISSUE TITLE
Psych 106 (FAR Master)

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#69]
**Which course contains the bug?**  
- Psych 106 (FAR Master
 
 
**Describe the error and/or your suggestion**  
Plugin alert for Learning Activity in Topic 1 is not working so content is not visible on moodle page. 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10885&section=2
2. Unit # 1        Topic #1         Activity#  1
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@dgaudet48 just want to check if you've resolved this issue.
If you didn't get a notification, perhaps assign yourself to all PSYC 106 issues (see Assignees section top right).

Also - @cmadland - are we working on a way to get notified when the card moves into the Review Requested column?

Otherwise, let's ask the ATAs to please notify the assigned ID.

**Comment by dgaudet48** [comment]
It has been fixed!

Thanks
